package com.openclassrooms.entities.enums;

public enum Brand {
    DELL, SAMSUNG, ACER, ASUS, HP, TOSHIBA, APPLE, MICROSOFT, GOOGLE, CANON, PANASONIC, SONY, LG, XIAOMI, OPPO, VIVO, HUAWEI, NOKIA, ONEPLUS, MOTOROLA, ALCATEL, BLACKBERRY, HTC, NEXUS
}
